[package]
name = "pactmockserver"
version = "0.1.0"
authors = []

[lib]
name = "pactmockserver"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.18.0"
libc = "0.2.9"
rustler_codegen = "0.18.0"
lazy_static = "0.2"
pact_mock_server = "0.4.0"
